console_title_template = '{{ .Folder }}'
version = 3

[palette]
  background = '{background}'
  foreground = '{foreground}'
  cursor = '{cursor}'
  color0 = '{color0}'
  color1 = '{color1}'
  color2 = '{color2}'
  color3 = '{color3}'
  color4 = '{color4}'
  color5 = '{color5}'
  color6 = '{color6}'
  color7 = '{color7}'
  color8 = '{color8}'
  color9 = '{color9}'
  color10 = '{color10}'
  color11 = '{color11}'
  color12 = '{color12}'
  color13 = '{color13}'
  color14 = '{color14}'
  color15 = '{color15}'
  
[transient_prompt]
  template = ' '
  foreground = 'foreground'
  background = 'transparent'

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = '<transparent,p:background></>'
    template = '{{.Icon}} '
    foreground = 'p:foreground'
    background = 'p:background'
    type = 'os'
    style = 'diamond'

    [blocks.segments.properties]
      arch = ''

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = '<transparent,p:background></>'
    template = '   {{.Name}} '
    foreground = 'p:foreground'
    background = 'p:background'
    type = 'shell'
    style = 'diamond'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = '<transparent,p:color1></>'
    template = '   MEM: {{ round .PhysicalPercentUsed .Precision }}% | {{ (div ((sub .PhysicalTotalMemory .PhysicalAvailableMemory)|float64) 1073741824.0) }}/{{ (div .PhysicalTotalMemory 1073741824.0) }}GB   '
    foreground = '#ffffff'
    background = 'p:color1'
    type = 'sysinfo'
    style = 'diamond'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ .FormattedMs }} '
    foreground = 'p:color2'
    background = 'p:color3'
    type = 'executiontime'
    style = 'diamond'

    [blocks.segments.properties]
      style = 'roundrock'
      threshold = 0.0

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    foreground = 'p:color4'
    background = 'p:color5'
    type = 'git'
    style = 'diamond'

    [blocks.segments.properties]
      branch_icon = ' '
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true
      fetch_worktree_count = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '╭─'
    type = 'text'
    style = 'plain'

  [[blocks.segments]]
    template = ' 󰄛 {{ .CurrentDate | date .Format }} |'
    type = 'time'
    style = 'plain'

    [blocks.segments.properties]
      time_format = '15:04'

  [[blocks.segments]]
    template = '  '
    type = 'root'
    style = 'plain'

  [[blocks.segments]]
    template = ' {{ .Path }} '
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      folder_icon = ' '
      folder_separator_icon = '  '
      home_icon = ' '

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '╰─ '
    type = 'status'
    style = 'plain'

    [blocks.segments.properties]
      always_enabled = true
